export interface OpenSourceFont {
  id: string;
  name: string;
  category: 'sans' | 'mono' | 'serif' | 'display';
  tailwindClass: string;
  cssFamily: string;
  description: string;
  bestFor: string;
  sampleHeadline: string;
  sampleBody: string;
  license: string;
}

export const OPEN_SOURCE_FONTS: OpenSourceFont[] = [
  {
    id: 'inter',
    name: 'Inter',
    category: 'sans',
    tailwindClass: 'font-inter',
    cssFamily: "'Inter', sans-serif",
    description: 'The definitive open-source UI typeface crafted for high legibility on computer screens.',
    bestFor: 'Modern dashboards, SaaS infographics, complex UI mockups',
    sampleHeadline: 'Precision Engineering & Scalable Systems',
    sampleBody: 'Crafted with micro-contrast tuned specifically for pixel grids and high-density displays.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'jakarta',
    name: 'Plus Jakarta Sans',
    category: 'sans',
    tailwindClass: 'font-jakarta',
    cssFamily: "'Plus Jakarta Sans', sans-serif",
    description: 'Clean modern geometric sans-serif with contemporary European proportions and crisp clarity.',
    bestFor: 'Modern tech landing pages, Stripe/Vercel-style graphics',
    sampleHeadline: 'Next-Gen Developer Experience & Tools',
    sampleBody: 'Clean geometric curves paired with structured stems produce an unmistakable premium feel.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'outfit',
    name: 'Outfit',
    category: 'sans',
    tailwindClass: 'font-outfit',
    cssFamily: "'Outfit', sans-serif",
    description: 'Energetic geometric display sans with balanced roundness and high-impact visual punch.',
    bestFor: 'Hero titles, punchy infographics, feature cards, banners',
    sampleHeadline: 'Build Fast. Ship Confidently. Scale Always.',
    sampleBody: 'Vibrant circular geometry that commands immediate attention in banners and slides.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'space-grotesk',
    name: 'Space Grotesk',
    category: 'display',
    tailwindClass: 'font-space',
    cssFamily: "'Space Grotesk', sans-serif",
    description: 'Proportional sans-serif variant based on Space Mono, infused with quirky retro-cyberpunk aesthetics.',
    bestFor: 'Web3, DevSecOps, cyberpunk themes, brutalist posters',
    sampleHeadline: 'DECENTRALIZED PROTOCOL ARCHITECTURE',
    sampleBody: 'Monospace heritage reborn with proportional elegance for cutting-edge technical graphics.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'syne',
    name: 'Syne',
    category: 'display',
    tailwindClass: 'font-syne',
    cssFamily: "'Syne', sans-serif",
    description: 'Avant-garde artistic typeface with extraordinary personality, wide letterforms, and bold curves.',
    bestFor: 'Creative branding, design studios, AI concepts, bold statements',
    sampleHeadline: 'CREATIVE INTELLIGENCE & VISION',
    sampleBody: 'Designed for unforgettable visual identity and striking artistic expression.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'jetbrains-mono',
    name: 'JetBrains Mono',
    category: 'mono',
    tailwindClass: 'font-mono',
    cssFamily: "'JetBrains Mono', monospace",
    description: 'Tailor-made for developers: increased x-height, distinct glyphs, and high scanning comfort.',
    bestFor: 'Code snippets, API endpoints, JSON previews, terminal output',
    sampleHeadline: 'async function settlePromises(tasks) {}',
    sampleBody: 'const status = result.status === "fulfilled" ? 200 : 500;',
    license: 'Apache 2.0 (100% Commercial Use)',
  },
  {
    id: 'fira-code',
    name: 'Fira Code',
    category: 'mono',
    tailwindClass: 'font-fira',
    cssFamily: "'Fira Code', monospace",
    description: 'Beloved programmer monospace font featuring comprehensive multi-character ligatures.',
    bestFor: 'Algorithm flowcharts, syntax demonstrations, equations',
    sampleHeadline: 'data.filter(x => x !== null) ==> true',
    sampleBody: 'Ligatures combine sequences like !==, >=, and -> into clean visual operators.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'playfair',
    name: 'Playfair Display',
    category: 'serif',
    tailwindClass: 'font-playfair',
    cssFamily: "'Playfair Display', serif",
    description: 'High-contrast transitional serif influenced by late 18th-century European Enlightenment print.',
    bestFor: 'Quotes, editorial callouts, luxury tech branding, storytelling',
    sampleHeadline: 'The Art of Thoughtful Software Design',
    sampleBody: '“Simplicity is prerequisite for reliability.” — Edsger W. Dijkstra',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'cinzel',
    name: 'Cinzel',
    category: 'serif',
    tailwindClass: 'font-cinzel',
    cssFamily: "'Cinzel', serif",
    description: 'Classical Roman inscriptional serif inspired by first-century Latin epigraphy.',
    bestFor: 'Certificates, monumental titles, badges, luxury achievements',
    sampleHeadline: 'HONORIS CAUSA & EXCELLENCE',
    sampleBody: 'Classical geometric proportions conveying timeless authority and milestone prestige.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'bebas-neue',
    name: 'Bebas Neue',
    category: 'display',
    tailwindClass: 'font-bebas',
    cssFamily: "'Bebas Neue', Impact, sans-serif",
    description: 'All-caps condensed powerhouse known as the undisputed king of bold headline posters and memes.',
    bestFor: 'Meme text, mega metrics, explosive stats, countdown banners',
    sampleHeadline: '10X PERFORMANCE MULTIPLIER',
    sampleBody: 'TIGHT ALL-CAPS LETTERFORMS ENGINEERED TO DOMINATE SOCIAL MEDIA FEEDS.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
  {
    id: 'comic-neue',
    name: 'Comic Neue',
    category: 'display',
    tailwindClass: 'font-comic',
    cssFamily: "'Comic Neue', cursive, sans-serif",
    description: 'The beloved, perfected open-source remake of Comic Sans for playful, funny developer memes.',
    bestFor: 'Developer memes, funny tech disclaimers, playful social infographics',
    sampleHeadline: '"It works on my machine! 🤷‍♂️"',
    sampleBody: 'Then we will ship your laptop to the client! No bugs detected on localhost:3000.',
    license: 'SIL Open Font License 1.1 (100% Commercial Use)',
  },
];
